apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  PORT: {{ .Values.config.port | quote }}

