apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.secret.database | quote }}
  MYSQL_USER: {{ .Values.secret.username | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.password | quote }}

